### ISSUE TITLE
parsegams is failing. 

### ISSUE THREAD

**Issue by 1ozturkbe** [timholy/GAMSFiles.jl#4]
Hello @timholy, I have been following your work in Julia dev for a while, definitely a fan. I came upon this repo since I am hoping to solve some optimization problems stored using .gms. However, it seems like you are no longer maintaining it, since even simple GAMS files are not successfully imported using more recent versions of Julia. 

I am assuming this is due to deprecations of certain functions (such as isalnum) as well as issues in parsing since Julia 1.x. I was wondering if you have interest in helping me revive this repo. It would be useful for myself and others in the optimization world to keep being able to solve test problems. If you have pointers with respect to where to start that would be great. Thanks!

**Comment by timholy** [comment]
Thanks for the offer of help! Gladly accepted. The first step would be to get the tests passing, that should make everything much easier.

**Comment by 1ozturkbe** [comment]
No problem. I have narrowed one of the critical issues in parsegams to inconsistent lexing of ".." in equation declaration, sometimes correctly to Dots("..") and sometimes incorrectly to 2 consecutive Dots(".")'s. Not exactly sure where the issue is occurring, since the lexer seems to have the right rules (lexer.jl, line 140). If you have any ideas let me know!

**Comment by timholy** [comment]
I'd just add a `@show pos c inrelation innumber hadexponent prevbool` at around this line https://github.com/timholy/GAMSFiles.jl/blob/46aa6230866a2368bf4d88d0dae1fb6a3a22958d/src/lexer.jl#L25
and then watch what happens.

**Comment by 1ozturkbe** [comment]
@timholy I [forked the repo](https://github.com/1ozturkbe/GAMSFiles.jl), fixed some deprecations and hacked the Dots("..") issue as best I could. As far as I can tell the lexer works as intended, but there are still parts of the parser that are proving to be problematic. This is also not helped by the fact that the parser is recursive, and there is one block comment for 400 lines of code. I could really use help.
 [The loop at line 223](https://github.com/1ozturkbe/GAMSFiles.jl/blob/924eda155707e6f231ba2a80b13877456f5690bc/src/parser.jl#L223) is confusing, because args seems to always be 1 element long? Also, [this assert](https://github.com/1ozturkbe/GAMSFiles.jl/blob/924eda155707e6f231ba2a80b13877456f5690bc/src/parser.jl#L268), which I have commented out for now, fails, but I can confirm that many tests pass without it. Is the parser supposed to recursively split GAMSFiles objects by order of operations? 
Perhaps you can shed some light into the parser so I don't have to reverse engineer everything. Thanks!

**Comment by 1ozturkbe** [comment]
Alright, I have narrowed issues to the process_ops! function. The @assert is triggered when a multiplication operation in a GCall isn't properly "processed". The multiple args always straddle a * operation.

**Comment by timholy** [comment]
Since I last worked on this repo 3 years ago, there's almost nothing useful I remember about the design. In particular, I don't know the answer to any of your questions above.

**Comment by timholy** [comment]
You can always start from scratch...there are times when that's easier.

**Comment by 1ozturkbe** [comment]
As of #5 this is resolved!
